language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install pyflakes --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 {{APP_NAME}}"
  - pyflakes -x W {{APP_NAME}}
script:
  - python setup.py test