language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
install:
  - pip install argparse --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coverage
  - pip install pep8 --use-mirrors
  - pip install pyflakes --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501 invoice"
  - pyflakes invoice
script:
  - python tests.py
  - coverage run tests.py
after_success: 
  - pip install coveralls
  - coveralls